server:
  port: 8083

spring:
  application:
    name: smartcampus-attendance

  datasource:
    url: jdbc:postgresql://localhost:5432/smartcampus
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: smartcampus_attendance
        format_sql: true

  flyway:
    enabled: true
    schemas: smartcampus_attendance
    default-schema: smartcampus_attendance
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: smartcampus-attendance
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "smartcampus.*"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/api/core/auth/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    smartcampus: info
